In [1]:
# import dependencies
import pandas as pd
import boto3
from sqlalchemy import create_engine
from io import StringIO
from config import aws_id, aws_secret, sql_pwd
import numpy as np

In [2]:

# Create Database Engine and extract merged_Final_allDatasets_left_df from Database
connection_string = f"postgres://postgres:{sql_pwd}@group-c-project-db.csna2pebfhlh.us-east-2.rds.amazonaws.com:5432/postgres"
engine = create_engine(connection_string)
interactive_df = pd.read_sql(sql="Interactive_ML_Movie_Data", con=engine)
interactive_df.head()

,index,Netflix,Hulu,Prime Video,Disney+,title,budget,company,country,director,...,writer,original_language,popularity,revenue,runtime,release_year,release_month,release_day,class,score_prediction
0,0,1.0,0.0,0.0,0.0,Inception,160000000.0,Warner Bros.,USA,Other,...,Other,en,167.6,825532764,148.0,2010,7,16,0,6.7
1,1,1.0,0.0,0.0,0.0,The Matrix,63000000.0,Warner Bros.,USA,Other,...,Other,en,104.3,463517383,136.0,1999,3,31,1,6.6
2,2,1.0,0.0,1.0,0.0,The Pianist,35000000.0,Other,France,Other,...,Other,en,50.6,120072577,150.0,2003,3,28,1,7.6
3,3,1.0,0.0,0.0,0.0,Django Unchained,100000000.0,Other,USA,Other,...,Quentin Tarantino,en,82.1,425368238,165.0,2012,12,25,0,7.3
4,4,1.0,0.0,0.0,0.0,Inglourious Basterds,75000000.0,Universal Pictures,USA,Other,...,Quentin Tarantino,en,72.6,319131050,153.0,2009,8,21,1,6.2

In [4]:
interactive_df.to_csv('Final_Datasets/Interactive_ML_Data.csv', encoding='utf-8')

In [6]:
 # create new column
interactive_df["filter_pop"] = ""
# create name for each class
interactive_df.loc[(interactive_df['class'] == 0), "filter_pop"] = "Underrated"
interactive_df.loc[(interactive_df['class'] == 1), "filter_pop"] = "Average Movie"
interactive_df.loc[(interactive_df['class'] == 2), "filter_pop"] = "Blockbuster"

In [9]:
interactive_df.head()

,index,Netflix,Hulu,Prime Video,Disney+,title,budget,company,country,director,...,original_language,popularity,revenue,runtime,release_year,release_month,release_day,class,score_prediction,filter_pop
0,0,1.0,0.0,0.0,0.0,Inception,160000000.0,Warner Bros.,USA,Other,...,en,167.6,825532764,148.0,2010,7,16,0,6.7,Underrated
1,1,1.0,0.0,0.0,0.0,The Matrix,63000000.0,Warner Bros.,USA,Other,...,en,104.3,463517383,136.0,1999,3,31,1,6.6,Average Movie
2,2,1.0,0.0,1.0,0.0,The Pianist,35000000.0,Other,France,Other,...,en,50.6,120072577,150.0,2003,3,28,1,7.6,Average Movie
3,3,1.0,0.0,0.0,0.0,Django Unchained,100000000.0,Other,USA,Other,...,en,82.1,425368238,165.0,2012,12,25,0,7.3,Underrated
4,4,1.0,0.0,0.0,0.0,Inglourious Basterds,75000000.0,Universal Pictures,USA,Other,...,en,72.6,319131050,153.0,2009,8,21,1,6.2,Average Movie

In [10]:
interactive_df.to_csv('Final_Datasets/Interactive_ML_Data.csv', encoding='utf-8')

In [29]:
 # create new column
interactive_df["streaming_service"] = ""
# create name for each class
interactive_df.loc[(interactive_df['Disney+'] == 1), "streaming_service"] = 'Disney+'
interactive_df.loc[(interactive_df['Prime Video'] == 1), "streaming_service"] = 'Prime Video'
interactive_df.loc[(interactive_df['Hulu'] == 1), "streaming_service"] = 'Hulu'
interactive_df.loc[(interactive_df['Netflix'] == 1), "streaming_service"] = 'Netflix'

In [30]:
interactive_df

,index,Netflix,Hulu,Prime Video,Disney+,title,budget,company,country,director,...,popularity,revenue,runtime,release_year,release_month,release_day,class,score_prediction,filter_pop,streaming_service
0,0,1.0,0.0,0.0,0.0,Inception,160000000.0,Warner Bros.,USA,Other,...,167.6,825532764,148.0,2010,7,16,0,6.7,Underrated,Netflix
1,1,1.0,0.0,0.0,0.0,The Matrix,63000000.0,Warner Bros.,USA,Other,...,104.3,463517383,136.0,1999,3,31,1,6.6,Average Movie,Netflix
2,2,1.0,0.0,1.0,0.0,The Pianist,35000000.0,Other,France,Other,...,50.6,120072577,150.0,2003,3,28,1,7.6,Average Movie,Netflix
3,3,1.0,0.0,0.0,0.0,Django Unchained,100000000.0,Other,USA,Other,...,82.1,425368238,165.0,2012,12,25,0,7.3,Underrated,Netflix
4,4,1.0,0.0,0.0,0.0,Inglourious Basterds,75000000.0,Universal Pictures,USA,Other,...,72.6,319131050,153.0,2009,8,21,1,6.2,Average Movie,Netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3006,3006,0.0,0.0,0.0,0.0,Next Friday,11000000.0,New Line Cinema,USA,Other,...,9.3,59827328,98.0,2000,1,12,0,6.5,Underrated,
3007,3007,0.0,0.0,0.0,0.0,Maleficent,180000000.0,Other,USA,Other,...,110.6,758539785,97.0,2014,5,30,0,6.1,Underrated,
3008,3008,0.0,0.0,0.0,0.0,Celebrity,12000000.0,Other,USA,Woody Allen,...,7.6,0,113.0,1998,11,20,0,6.1,Underrated,
3009,3009,0.0,0.0,0.0,0.0,X-Men Origins: Wolverine,150000000.0,Twentieth Century Fox Film Corporation,USA,Other,...,6.0,373062864,107.0,2009,5,1,0,6.0,Underrated,
3010,3010,0.0,0.0,0.0,0.0,House Party 2,5000000.0,Other,USA,Other,...,3.7,0,97.0,1991,10,23,0,6.0,Underrated,

In [23]:
interactive_df.to_csv('Final_Datasets/Interactive_ML_Data.csv', encoding='utf-8')